### ISSUE TITLE
Remote cart saving and deleting should be more intuitive

### ISSUE THREAD

**Issue by abutcher** [abutcher/juicer#23]
I don't think this is clear now because in order to remotely save a cart you have to `juicer cart push` it. Meaning that you have to push the items in the cart for the cart to exist remotely. Maybe you don't want to push the items in the cart but you want save the cart remotely so that someone else can push it?

```
juicer cart push my-cart
```

And in order to delete your cart locally you have to delete the cart file. If we `juicer cart delete` a cart, it's gone from everywhere. See next.

```
rm ~/.config/juicer/carts/my-cart.json
```

Deleting a cart with juicer will blow it away everywhere, locally and on remote. If you've deleted it, it's gone from the remote for good.

```
juicer cart delete my-cart
```

I think this behavior should be made a lot more clear by changing how these commands work / adding different commands.

**Comment by tbielawa** [comment]
I've seen some package type management commands which use ``--remote`` type options. These options instruct the command to operate **explicitly** and **only** on remote-items. That said, I think we could take this idea and manipulate this idea to do something close to what you're describing above.

(This is a really rough-idea. It is not well thought-out, and probably has some gaps/conflicts in terms of implementation ideas. But hey, it's just a first draft :) )

# new command signature

    juicer cart delete [ --remote | --local ] CARTNAME
        Delete a juicer cart. Default behavior deletes any locally cached copie
        as well as remote copies stored in MongoDB.

        options

        -r, --remote          delete the cart on the remote side only (ignores any cached cart definitions)
        -l,--local            delete the cart which is cached locally (does not destroy remote cart definitions)

# delete remote stuff
    juicer cart delete --remote omfg_hotfix_2

The cart stored in MongoDB named ``omfg_hotfix_2`` will be deleted (if it exists)

# delete local (cached) stuff
    juicer cart delete --local omfg_hotfix_2

The cart stored locally in ``CART_LOCATION`` named ``omfg_hotfix_2`` will be deleted (if it exists)


# next?

Those are just some first thoughts I had when I saw this issue.

**Comment by abutcher** [comment]
@tbielawa I am a big fan of `--remote` and `--local` for `juicer cart delete`.

In addition to these, I think we need a `juicer cart (publish|remote-save|save --remote)` that places the cart on remote but doesn't upload any of the items. `juicer cart push` can continue to update remote carts as a side-effect of pushing.

**Comment by tbielawa** [comment]
@abutcher **yes yes yes**

For those commands which send items over the network we may want to include plainly obvious disclaimers for specific use cases. I guess we can carts whose items are not uploaded into pulp "thin carts". They describe the cart, but the items described are not present in the system already.

For example:

If one were to create a cart which consisted entirely of items present on the local filesystem, there is not **much** value in pushing a thin cart to the cart host.

However, if one were to create a cart which consisted entirely of *remote* items, then the potential value gained from pushing that thin cart is much greater. A user could push a cart with all *remote* items from their local workstation. Then another user (or the same) could manipulate that cart from any other work station.

# wait, what about plugins?

We need to think smart about the possible work-flows this enables. If one were to push a thin-cart to the cart host and attempt to promote said cart, how then, for example, are plugins like RPM Sign applied? We would obviously need some sort of way to indicate that the items in the cart have not been pushed into the pulp server proper, additionally, it must be clear that **before** any defined plugins can run that:

1. The remote item(s) must first be fetched locally
1. The fetched items will be filtered through the appropriate plugin chain
1. The fetched items are then pushed to the pulp host

**Comment by abutcher** [comment]
@tbielawa The plugins part should work without any changes. When we attempt to push a cart that is not on our system we could pull that cart and push it. Pushing a cart with remote items **always** downloads them first so a plugin could be applied.

Note: This was requested once before https://github.com/juicer/juicer/issues/231

**Comment by abutcher** [comment]
To summarize where this issue stands:
* We need a way to save carts (*thin carts*) remotely without uploading all of the items in that cart.
* When pushing a cart, if it does not exist locally (ie it is a *thin cart* that exists only on remote), pull it and push it. Bop it.

**Comment by tbielawa** [comment]
* twist it

**Comment by abutcher** [comment]
How about...

`juicer cart create` will have `--local` and `--remote` options just like cart deletion, defaulting to both.

`juicer cart push` will have a `--thin` or something similar that just saves the cart on the remote without pushing it. Default will push items and save remotely.

**Comment by tbielawa** [comment]
sounds smart to me
