### ISSUE TITLE
Package juicer

### ISSUE THREAD

**Issue by abutcher** [abutcher/juicer#3]

**Comment by tbielawa** [comment]
Began working out most of this issue in e743ec03820164c0d49da71df71b182d8df94546

Note, **mostly**, I didn't add any package deps yet. But it's a start!

**Comment by tbielawa** [comment]
I plan on spinning up an AWS instance later tonight and working out what all the current deps are. Once that's complete I'll update the spec file and close this issue out.

**Comment by abutcher** [comment]
Added dependencies and included a Dockerfile for testing. I've also got a copr repo that will be added to install docs.
